"""User table

Revision ID: 0d3bce32de32
Revises:
Create Date: 2023-06-27 17:44:35.677408

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0d3bce32de32"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("session_id", sa.String(length=150), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("profile_link", sa.String(length=100), nullable=True),
        sa.Column("premium", sa.Boolean(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("birthday", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=50), nullable=True),
        sa.Column("area_code", sa.String(length=20), nullable=True),
        sa.Column("height_unit_pref", sa.String(length=50), nullable=True),
        sa.Column("weight_unit_pref", sa.String(length=50), nullable=True),
        sa.Column("date_format_pref", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_account")
    # ### end Alembic commands ###
