services:
  app:
    image: grau:latest
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://dan:testing123@db/train
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: testing123
      POSTGRES_USER: dan
      POSTGRES_DB: train
    ports:
      - 5432:5432

