services:
  app:
    image: grau:latest
    env_file:
      - .app_env
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    env_file:
      - .db_env
    ports:
      - 5432:5432
